-- Add AuditAction enum values for hard delete operations

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PROJECT_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVOICE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_DELETED';
