-- Add resource-allocation values to AuditAction enum

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RESOURCE_ALLOCATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RESOURCE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RESOURCE_DEALLOCATED';
