-- Add new AuditAction enum values for expense workflow and hard deletes

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_SUBMITTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PROJECT_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_DELETED';
